const jsonMappings = {
  ai: "data/ai.json",
  bash: "data/bash.json",
  book: "data/book.json",
  code: "data/code.json",
  cpp: "data/cpp.json",
  css: "data/css.json",
  db: "data/db.json",
  go: "data/go.json",
  html: "data/html.json",
  java: "data/java.json",
  js: "data/js.json",
  lifestyle: "data/lifestyle.json",
  lua: "data/lua.json",
  news: "data/news.json",
  py: "data/py.json",
  rb: "data/rb.json",
  rs: "data/rs.json",
  software: "data/software.json",
  sql: "data/sql.json",
  ts: "data/ts.json",
  yt: "data/yt.json",
  vet_book: "data/vet_book.json",
  vet_labs: "data/vet_labs.json",
  vet_content: "data/vet_content.json",
  vet_yt: "data/vet_yt.json",
  vet: "data/vet.json",
};
