const jsonMappings = {
  about_code: "data/about-code.json",
  about_home: "data/about-home.json",
  about_vet: "data/about-vet.json",
  ai: "data/ai.json",
  book: "data/book.json",
  code: "data/code.json",
  db: "data/db.json",
  news: "data/news.json",
  software: "data/software.json",
  vet: "data/vet.json",
  vet_book: "data/vet_book.json",
  vet_content: "data/vet_content.json",
  vet_labs: "data/vet_labs.json",
  yt: "data/yt.json",
};
